import { Response } from "express";
import AiService from "../ai/ai.service";
import IdeaRepository from "../idea/idea.repository";
import FeatureRepository from "../feature/feature.repository";
import TaskRepository from "../task/task.repository";
import { handoffRepository } from "./workflow.repository";
import { buildHandoffZip, IZipArtifact } from "./zip-archiver";
import { buildTechSpecPrompt } from "./prompts/technical-spec.prompt";
import { buildDatabaseSpecPrompt } from "./prompts/database-spec.prompt";
import { buildApiSpecPrompt } from "./prompts/api-spec.prompt";
import { buildCodingStandardsPrompt } from "./prompts/coding-standards.prompt";
import { buildRoadmapPrompt } from "./prompts/roadmap.prompt";
import { IHandoffCompilerVariables } from "./prompts/handoff-variables";
import { IFeature } from "../feature/types/IFeature";
import { ITask } from "../task/types/ITask";
import AppError from "../../utils/app-error";
import PrismaClientSingleton from "../../data-server-clients/prisma-client";

// ---------------------------------------------------------------
// SSE writer helper
// ---------------------------------------------------------------
export class SSEStreamWriter {
    constructor(private res: Response) {}

    write(event: string, data: object) {
        this.res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
    }

    progress(step: string, percent: number) {
        this.write("progress", { step, percent });
    }

    log(message: string) {
        this.write("log", { message });
    }

    complete(packageId: string, version: number) {
        this.write("complete", { packageId, version });
    }

    error(message: string) {
        this.write("error", { message });
    }
}

// ---------------------------------------------------------------
// Build master prompt (AI_IDE_START_HERE.md)
// ---------------------------------------------------------------
function buildMasterPrompt(vars: IHandoffCompilerVariables): string {
    return `# AI IDE Implementation Instructions — Start Here

You are an expert AI software engineer. You are tasked with implementing the software system defined in this handoff package.

## 1. Project Context
- **Project Name**: ${vars.ideaName}
- **Idea Description**: ${vars.ideaText}

## 2. Directory Map & Reading Order
Please read files in this sequence before writing any code:
1. \`AI_IDE_START_HERE.md\` (This file) — understand goal and rules
2. \`specifications/technical-specification.md\` — stack and environment
3. \`specifications/coding-standards.md\` — style and patterns
4. \`specifications/database-specification.md\` — schema and entities
5. \`specifications/api-specification.md\` — route contracts
6. \`implementation/implementation-roadmap.md\` — ordered task phases

## 3. Research Context
- \`research/research-summary.md\` — market research and competitor analysis
- \`documents/\` — PRD and BRD for product requirements

## 4. Diagrams
All diagrams in \`diagrams/\` are Mermaid format (.mmd). Read them to understand the system architecture, entity relationships, and user flows.

## 5. Strict Execution Rules
1. **Zero-Guessing Contracts**: Implement APIs and schemas EXACTLY as defined in \`specifications/\`.
2. **Compile-Check Cycle**: Compile and run tests at the end of each phase before moving to the next.
3. **No Orphan Code**: Do not create placeholder files or comment out existing code.
4. **Dependency Enforcement**: Do not start a task unless its dependencies (declared in \`implementation-roadmap.md\`) are complete.

## 6. Status Tracking
Create an \`IMPLEMENTATION_STATUS.md\` file at the project root. Update it after completing each phase with: phase name, tasks done, test results, and next steps.
`;
}

// ---------------------------------------------------------------
// Build .cursorrules file
// ---------------------------------------------------------------
function buildCursorRules(vars: IHandoffCompilerVariables): string {
    return `# Cursor Rules — ${vars.ideaName}

## Project Context
This project was generated by PAD (Product Architecture Designer).
Always refer to the \`handoff-package/\` directory for all specifications before writing code.

## Key Rules
- Read \`specifications/\` before implementing ANY feature
- Follow \`specifications/coding-standards.md\` for naming and patterns
- Use exact column/field names from \`specifications/database-specification.md\`
- Match exact route paths from \`specifications/api-specification.md\`
- Never guess — if unclear, read the spec first
`;
}

// ---------------------------------------------------------------
// Assemble static artifacts (upstream data verbatim)
// ---------------------------------------------------------------
function buildStaticArtifacts(vars: IHandoffCompilerVariables): IZipArtifact[] {
    const artifacts: IZipArtifact[] = [];

    // Research
    if (vars.researchSummary) {
        artifacts.push({
            filePath: "research/research-summary.md",
            content: `# Research Summary\n\n${vars.researchSummary}`,
        });
    }

    // Documents
    if (vars.prdContent) {
        artifacts.push({
            filePath: "documents/product-requirements-document.md",
            content: vars.prdContent,
        });
    }
    if (vars.brdContent) {
        artifacts.push({
            filePath: "documents/business-requirements-document.md",
            content: vars.brdContent,
        });
    }

    // Diagrams
    if (vars.diagrams) {
        for (const diagram of vars.diagrams) {
            const fileName = diagram.type.toLowerCase().replace(/_/g, "-");
            artifacts.push({
                filePath: `diagrams/${fileName}.mmd`,
                content: diagram.mermaidCode,
            });
        }
    }

    // Features JSON
    const featuresJson = vars.features.map((f) => ({
        id: f.id,
        title: f.title,
        description: f.description,
        priority: f.priority,
        taskCount: f.tasks.length,
    }));
    artifacts.push({
        filePath: "features/feature-requirements.json",
        content: JSON.stringify(featuresJson, null, 2),
    });

    // Tasks backlog JSON
    const taskBacklog = vars.features.flatMap((f) =>
        f.tasks.map((t: ITask) => ({
            id: t.id,
            featureId: f.id,
            featureTitle: f.title,
            title: t.title,
            description: t.description,
            priority: t.priority,
            estimatedEffort: t.estimatedEffort,
        }))
    );
    artifacts.push({
        filePath: "tasks/task-backlog.json",
        content: JSON.stringify(taskBacklog, null, 2),
    });

    // Dependency matrix JSON
    artifacts.push({
        filePath: "tasks/dependency-matrix.json",
        content: JSON.stringify(vars.taskDependenciesMap ?? {}, null, 2),
    });

    return artifacts;
}

// ---------------------------------------------------------------
// Main compiler orchestrator
// ---------------------------------------------------------------
export class HandoffCompilerService {
    static async compilePackage(ideaId: string, sse: SSEStreamWriter): Promise<void> {
        const ideaRepo = IdeaRepository.getInstance();
        const featureRepo = FeatureRepository.getInstance();
        const taskRepo = TaskRepository.getInstance();

        // 1. Gather input data
        sse.progress("Gathering workspace context...", 5);

        const idea = await ideaRepo.getIdeaById(ideaId);
        if (!idea) {
            sse.error("Idea not found.");
            return;
        }

        const features = await featureRepo.getFeaturesByIdeaId(ideaId);
        if (!features || features.length === 0) {
            sse.error("No features found. Run Module 4 first.");
            return;
        }

        // Hydrate tasks per feature
        const featuresWithTasks = await Promise.all(
            features.map(async (f) => {
                const tasks = await taskRepo.getTasksByFeatureId(f.id);
                return { ...f, tasks } as IFeature & { tasks: ITask[] };
            })
        );

        // Build dependency map
        const taskDependenciesMap: Record<string, string[]> = {};
        for (const f of featuresWithTasks) {
            for (const t of f.tasks) {
                const taskWithDeps = await taskRepo.getTaskWithDependencies(t.id);
                if (taskWithDeps?.dependencies) {
                    taskDependenciesMap[t.id] = taskWithDeps.dependencies.map(
                        (d: any) => d.dependsOnTaskId
                    );
                }
            }
        }

        // Fetch documents (PRD/BRD)
        const prisma = PrismaClientSingleton.getPrismaClient();

        const documents = await prisma.document.findMany({ where: { ideaId } });
        const prd = documents.find((d: any) => d.type === "PRD");
        const brd = documents.find((d: any) => d.type === "BRD");

        // Fetch diagrams
        const diagrams = await prisma.diagram.findMany({
            where: {
                ideaId,
                mermaidCode: { not: "" },
                status: { not: "repair_failed" },
            },
        });

        // Fetch research
        const researchSummary =
            idea.researchResult
                ? (idea.researchResult as any).summary ||
                  JSON.stringify(idea.researchResult)
                : undefined;

        // Fetch user guidelines (RAG)
        let userGuidelines: string | undefined;
        try {
            const { QdrantClient } = require("../../data-server-clients/qdrant");
            const guidelines = await QdrantClient.searchGuidelines(
                idea.userId,
                idea.refinedText || idea.rawText,
                6
            );
            if (guidelines.length > 0) {
                userGuidelines = guidelines
                    .map((g: any, i: number) => `[${i + 1}] ${g.title}:\n${g.text}`)
                    .join("\n\n");
            }
        } catch (_) {
            // Guidelines optional
        }

        const ideaName = (idea.refinedText || idea.rawText).split("\n")[0].slice(0, 80);
        const ideaText = idea.refinedText || idea.rawText;

        const vars: IHandoffCompilerVariables = {
            ideaText,
            ideaName,
            features: featuresWithTasks,
            researchSummary,
            prdContent: prd?.content,
            brdContent: brd?.content,
            diagrams: diagrams.map((d: any) => ({
                type: d.type,
                title: d.title,
                mermaidCode: d.mermaidCode,
            })),
            taskDependenciesMap,
            userGuidelines,
        };

        // 2. Create DB package record
        const version = await handoffRepository.getNextVersion(ideaId);
        const pkg = await handoffRepository.createPackage(ideaId, version);

        // 3. Generate specs sequentially (each returns plain markdown)
        sse.progress("Generating Technical Specification...", 15);
        sse.log("Calling LLM: technical-specification.md");
        const techSpec = await AiService.callLLM(buildTechSpecPrompt(vars), false, undefined, idea.userId);
        await handoffRepository.upsertArtifact(pkg.id, "specifications/technical-specification.md", "Technical Specification", techSpec, "markdown");

        sse.progress("Generating Database Specification...", 30);
        sse.log("Calling LLM: database-specification.md");
        const dbSpec = await AiService.callLLM(buildDatabaseSpecPrompt(vars), false, undefined, idea.userId);
        await handoffRepository.upsertArtifact(pkg.id, "specifications/database-specification.md", "Database Specification", dbSpec, "markdown");

        sse.progress("Generating API Specification...", 45);
        sse.log("Calling LLM: api-specification.md");
        const apiSpec = await AiService.callLLM(buildApiSpecPrompt(vars, techSpec), false, undefined, idea.userId);
        await handoffRepository.upsertArtifact(pkg.id, "specifications/api-specification.md", "API Specification", apiSpec, "markdown");

        sse.progress("Generating Coding Standards...", 60);
        sse.log("Calling LLM: coding-standards.md");
        const codingStandards = await AiService.callLLM(buildCodingStandardsPrompt(vars, techSpec), false, undefined, idea.userId);
        await handoffRepository.upsertArtifact(pkg.id, "specifications/coding-standards.md", "Coding Standards", codingStandards, "markdown");

        sse.progress("Generating Implementation Roadmap...", 75);
        sse.log("Calling LLM: implementation-roadmap.md");
        const roadmap = await AiService.callLLM(
            buildRoadmapPrompt(vars, { techSpec, dbSpec, apiSpec, codingStandards }),
            false,
            undefined,
            idea.userId
        );
        await handoffRepository.upsertArtifact(pkg.id, "implementation/implementation-roadmap.md", "Implementation Roadmap", roadmap, "markdown");

        // 4. Assemble static artifacts
        sse.progress("Assembling upstream artifacts...", 82);
        sse.log("Packaging: research, documents, diagrams, features, tasks");
        const staticArtifacts = buildStaticArtifacts(vars);
        for (const artifact of staticArtifacts) {
            const title = artifact.filePath.split("/").pop()?.replace(/\.(md|json|mmd)$/, "").replace(/-/g, " ") ?? artifact.filePath;
            const fileType = artifact.filePath.endsWith(".mmd")
                ? "mermaid"
                : artifact.filePath.endsWith(".json")
                ? "json"
                : "markdown";
            await handoffRepository.upsertArtifact(pkg.id, artifact.filePath, title, artifact.content, fileType);
        }

        // 5. Build master prompt and .cursorrules (stored in DB as artifacts)
        const masterPrompt = buildMasterPrompt(vars);
        await handoffRepository.upsertArtifact(pkg.id, "AI_IDE_START_HERE.md", "AI IDE Start Here", masterPrompt, "markdown");

        const cursorRules = buildCursorRules(vars);
        await handoffRepository.upsertArtifact(pkg.id, ".cursorrules", "Cursor Rules", cursorRules, "markdown");

        // 6. Build ZIP
        sse.progress("Building ZIP archive...", 90);
        sse.log("Compressing package...");

        const allArtifacts = await handoffRepository.getArtifactsByPackageId(pkg.id);
        const zipArtifacts: IZipArtifact[] = allArtifacts.map((a: any) => ({
            filePath: a.filePath,
            content: a.content,
        }));

        const zipPath = await buildHandoffZip(ideaId, version, zipArtifacts);

        // 7. Mark package ready
        await handoffRepository.updatePackageStatus(pkg.id, "ready", zipPath);

        sse.progress("Package ready!", 100);
        sse.complete(pkg.id, version);
    }

    // Compile all artifacts into a single clipboard-ready string
    static async compileMasterPromptString(packageId: string): Promise<string> {
        const artifacts = await handoffRepository.getArtifactsByPackageId(packageId);
        if (!artifacts || artifacts.length === 0) {
            throw new AppError(404, "Package has no artifacts.");
        }

        const orderedPaths = [
            "AI_IDE_START_HERE.md",
            "specifications/technical-specification.md",
            "specifications/coding-standards.md",
            "specifications/database-specification.md",
            "specifications/api-specification.md",
            "implementation/implementation-roadmap.md",
        ];

        let output = "";

        for (const filePath of orderedPaths) {
            const artifact = artifacts.find((a: any) => a.filePath === filePath);
            if (artifact) {
                output += `\n\n---\n## File: ${artifact.filePath}\n\n${artifact.content}`;
            }
        }

        return output.trim();
    }
}
