import {
  Injectable,
  NotFoundException,
} from "@nestjs/common";
import { Response } from "express";
import AiService from "../ai/ai.service";
import { IdeaRepository } from "../idea/idea.repository";
import { DocumentRepository } from "../document/document.repository";
import { DiagramRepository } from "../diagram/diagram.repository";
import { HandoffRepository } from "./workflow.repository";
import { buildHandoffZip, IZipArtifact } from "./zip-archiver";
import { buildTechSpecPrompt } from "./prompts/technical-spec.prompt";
import { buildDatabaseSpecPrompt } from "./prompts/database-spec.prompt";
import { buildApiSpecPrompt } from "./prompts/api-spec.prompt";
import { buildCodingStandardsPrompt } from "./prompts/coding-standards.prompt";
import { buildRoadmapPrompt } from "./prompts/roadmap.prompt";
import { IHandoffCompilerVariables } from "./prompts/handoff-variables";

// ---------------------------------------------------------------
// SSE writer helper
// ---------------------------------------------------------------
export class SSEStreamWriter {
  constructor(private res: Response) {}

  write(event: string, data: object) {
    this.res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
  }

  progress(step: string, percent: number) {
    this.write("progress", { step, percent });
  }

  log(message: string) {
    this.write("log", { message });
  }

  complete(packageId: string, version: number) {
    this.write("complete", { packageId, version });
  }

  error(message: string) {
    this.write("error", { message });
  }
}

// ---------------------------------------------------------------
// Build master prompt (AI_IDE_START_HERE.md)
// ---------------------------------------------------------------
function buildMasterPrompt(vars: IHandoffCompilerVariables): string {
  return `# AI IDE Implementation Instructions — Start Here

You are an expert AI software engineer. You are tasked with implementing the software system defined in this handoff package.

## 1. Project Context
- **Project Name**: ${vars.ideaName}
- **Idea Description**: ${vars.ideaText}

## 2. Directory Map & Reading Order
Please read files in this sequence before writing any code:
1. \`AI_IDE_START_HERE.md\` (This file) — understand goal and rules
2. \`specifications/technical-specification.md\` — stack and environment
3. \`specifications/coding-standards.md\` — style and patterns
4. \`specifications/database-specification.md\` — schema and entities
5. \`specifications/api-specification.md\` — route contracts
6. \`implementation/implementation-roadmap.md\` — ordered task phases

## 3. Documents
- \`documents/\` — PRD and BRD for product and business requirements

## 4. Diagrams
All diagrams in \`diagrams/\` are Mermaid format (.mmd). Read them to understand the system architecture, entity relationships, and user flows.

## 5. Strict Execution Rules
1. **Zero-Guessing Contracts**: Implement APIs and schemas EXACTLY as defined in \`specifications/\`.
2. **Compile-Check Cycle**: Compile and run tests at the end of each phase before moving to the next.
3. **No Orphan Code**: Do not create placeholder files or comment out existing code.
4. **Dependency Enforcement**: Do not start a task unless its dependencies (declared in \`implementation-roadmap.md\`) are complete.

## 6. Status Tracking
Create an \`IMPLEMENTATION_STATUS.md\` file at the project root. Update it after completing each phase with: phase name, tasks done, test results, and next steps.
`;
}

// ---------------------------------------------------------------
// Build .cursorrules file
// ---------------------------------------------------------------
function buildCursorRules(vars: IHandoffCompilerVariables): string {
  return `# Cursor Rules — ${vars.ideaName}

## Project Context
This project was generated by PAD (Product Architecture Designer).
Always refer to the \`handoff-package/\` directory for all specifications before writing code.

## Key Rules
- Read \`specifications/\` before implementing ANY feature
- Follow \`specifications/coding-standards.md\` for naming and patterns
- Use exact column/field names from \`specifications/database-specification.md\`
- Match exact route paths from \`specifications/api-specification.md\`
- Never guess — if unclear, read the spec first
`;
}

// ---------------------------------------------------------------
// Assemble static artifacts (upstream data verbatim)
// ---------------------------------------------------------------
function buildStaticArtifacts(vars: IHandoffCompilerVariables): IZipArtifact[] {
  const artifacts: IZipArtifact[] = [];

  // Documents
  if (vars.prdContent) {
    artifacts.push({
      filePath: "documents/product-requirements-document.md",
      content: vars.prdContent,
    });
  }
  if (vars.brdContent) {
    artifacts.push({
      filePath: "documents/business-requirements-document.md",
      content: vars.brdContent,
    });
  }

  // Diagrams
  if (vars.diagrams) {
    for (const diagram of vars.diagrams) {
      const fileName = diagram.type.toLowerCase().replace(/_/g, "-");
      artifacts.push({
        filePath: `diagrams/${fileName}.mmd`,
        content: diagram.mermaidCode,
      });
    }
  }

  return artifacts;
}

// ---------------------------------------------------------------
// Main compiler orchestrator
// ---------------------------------------------------------------
@Injectable()
export class HandoffCompilerService {
  private static instance: HandoffCompilerService;

  constructor(
    private readonly handoffRepo: HandoffRepository,
    private readonly ideaRepo: IdeaRepository,
    private readonly docRepo: DocumentRepository,
    private readonly diagRepo: DiagramRepository,
  ) {
    HandoffCompilerService.instance = this;
  }

  static getInstance(): HandoffCompilerService {
    return HandoffCompilerService.instance;
  }

  async compilePackage(
    ideaId: string,
    sse: SSEStreamWriter,
  ): Promise<void> {
    sse.progress("Gathering workspace context...", 5);

    const idea = await this.ideaRepo.findById(ideaId);
    if (!idea) {
      sse.error("Idea not found.");
      return;
    }

    const documents = await this.docRepo.getDocumentsByIdeaId(ideaId);
    const prd = documents.find((d) => d.type === "PRD");
    const brd = documents.find((d) => d.type === "BRD");

    const diagrams = await this.diagRepo.getDiagramsByIdeaId(ideaId);
    const validDiagrams = diagrams.filter(
      (d) => d.mermaidCode && d.status !== "repair_failed",
    );

    let userGuidelines: string | undefined;
    try {
      const { QdrantClient } = require("../../data-server-clients/qdrant");
      const guidelines = await QdrantClient.searchGuidelines(
        idea.userId,
        idea.businessDescription || idea.refinedText || idea.rawText,
        6,
      );
      if (guidelines && guidelines.length > 0) {
        userGuidelines = guidelines
          .map((g: any, i: number) => `[${i + 1}] ${g.title}:\n${g.text}`)
          .join("\n\n");
      }
    } catch (_) {
      // Optional guidelines
    }

    const ideaText =
      idea.businessDescription || idea.refinedText || idea.rawText;
    const ideaName = ideaText.split("\n")[0].slice(0, 80);

    const vars: IHandoffCompilerVariables = {
      ideaText,
      ideaName,
      prdContent: prd?.content,
      brdContent: brd?.content,
      diagrams: validDiagrams.map((d) => ({
        type: d.type,
        title: d.title,
        mermaidCode: d.mermaidCode,
      })),
      documents: documents.map((d) => ({
        type: d.type,
        title: d.title,
        content: d.content,
      })),
      userGuidelines,
    };

    // 2. Create DB package record
    const version = await this.handoffRepo.getNextVersion(ideaId);
    const pkg = await this.handoffRepo.createPackage(ideaId, version);

    // 3. Generate specs sequentially
    sse.progress("Generating Technical Specification...", 15);
    sse.log("Calling LLM: technical-specification.md");
    const techSpec = await AiService.callLLM(
      buildTechSpecPrompt(vars),
      false,
      undefined,
      idea.userId,
    );
    await this.handoffRepo.upsertArtifact(
      pkg.id,
      "specifications/technical-specification.md",
      "Technical Specification",
      techSpec,
      "markdown",
    );

    sse.progress("Generating Database Specification...", 30);
    sse.log("Calling LLM: database-specification.md");
    const dbSpec = await AiService.callLLM(
      buildDatabaseSpecPrompt(vars),
      false,
      undefined,
      idea.userId,
    );
    await this.handoffRepo.upsertArtifact(
      pkg.id,
      "specifications/database-specification.md",
      "Database Specification",
      dbSpec,
      "markdown",
    );

    sse.progress("Generating API Specification...", 45);
    sse.log("Calling LLM: api-specification.md");
    const apiSpec = await AiService.callLLM(
      buildApiSpecPrompt(vars, techSpec),
      false,
      undefined,
      idea.userId,
    );
    await this.handoffRepo.upsertArtifact(
      pkg.id,
      "specifications/api-specification.md",
      "API Specification",
      apiSpec,
      "markdown",
    );

    sse.progress("Generating Coding Standards...", 60);
    sse.log("Calling LLM: coding-standards.md");
    const codingStandards = await AiService.callLLM(
      buildCodingStandardsPrompt(vars, techSpec),
      false,
      undefined,
      idea.userId,
    );
    await this.handoffRepo.upsertArtifact(
      pkg.id,
      "specifications/coding-standards.md",
      "Coding Standards",
      codingStandards,
      "markdown",
    );

    sse.progress("Generating Implementation Roadmap...", 75);
    sse.log("Calling LLM: implementation-roadmap.md");
    const roadmap = await AiService.callLLM(
      buildRoadmapPrompt(vars, {
        techSpec,
        dbSpec,
        apiSpec,
        codingStandards,
      }),
      false,
      undefined,
      idea.userId,
    );
    await this.handoffRepo.upsertArtifact(
      pkg.id,
      "implementation/implementation-roadmap.md",
      "Implementation Roadmap",
      roadmap,
      "markdown",
    );

    // 4. Assemble static artifacts
    sse.progress("Assembling upstream artifacts...", 82);
    sse.log("Packaging: documents, diagrams");
    const staticArtifacts = buildStaticArtifacts(vars);
    for (const artifact of staticArtifacts) {
      const title =
        artifact.filePath
          .split("/")
          .pop()
          ?.replace(/\.(md|json|mmd)$/, "")
          .replace(/-/g, " ") ?? artifact.filePath;
      const fileType = artifact.filePath.endsWith(".mmd")
        ? "mermaid"
        : artifact.filePath.endsWith(".json")
        ? "json"
        : "markdown";
      await this.handoffRepo.upsertArtifact(
        pkg.id,
        artifact.filePath,
        title,
        artifact.content,
        fileType,
      );
    }

    // 5. Build master prompt and .cursorrules
    const masterPrompt = buildMasterPrompt(vars);
    await this.handoffRepo.upsertArtifact(
      pkg.id,
      "AI_IDE_START_HERE.md",
      "AI IDE Start Here",
      masterPrompt,
      "markdown",
    );

    const cursorRules = buildCursorRules(vars);
    await this.handoffRepo.upsertArtifact(
      pkg.id,
      ".cursorrules",
      "Cursor Rules",
      cursorRules,
      "markdown",
    );

    // 6. Build ZIP
    sse.progress("Building ZIP archive...", 90);
    sse.log("Compressing package...");

    const allArtifacts = await this.handoffRepo.getArtifactsByPackageId(pkg.id);
    const zipArtifacts: IZipArtifact[] = allArtifacts.map((a) => ({
      filePath: a.filePath,
      content: a.content,
    }));

    const zipPath = await buildHandoffZip(ideaId, version, zipArtifacts);

    // 7. Mark package ready
    await this.handoffRepo.updatePackageStatus(pkg.id, "ready", zipPath);

    sse.progress("Package ready!", 100);
    sse.complete(pkg.id, version);
  }

  async compileMasterPromptString(packageId: string): Promise<string> {
    const artifacts = await this.handoffRepo.getArtifactsByPackageId(packageId);
    if (!artifacts || artifacts.length === 0) {
      throw new NotFoundException("Package has no artifacts.");
    }

    const orderedPaths = [
      "AI_IDE_START_HERE.md",
      "specifications/technical-specification.md",
      "specifications/coding-standards.md",
      "specifications/database-specification.md",
      "specifications/api-specification.md",
      "implementation/implementation-roadmap.md",
    ];

    let output = "";

    for (const filePath of orderedPaths) {
      const artifact = artifacts.find((a) => a.filePath === filePath);
      if (artifact) {
        output += `\n\n---\n## File: ${artifact.filePath}\n\n${artifact.content}`;
      }
    }

    return output.trim();
  }
}

export default HandoffCompilerService;
